
/*
 * This file was generated by the SOM Compiler.
 * FileName: pileof.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.2
 *     SOM Emitter emith: 2.41
 */

/*
 * 
 * 
 *    Module Name: PILEOF
 * 
 *    OS/2 Work Place Shell Sample Program
 * 
 * 
 */


#ifndef SOM_PileOf_h
#define SOM_PileOf_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef PileOf
#define PileOf SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */
#ifndef M_PileOf
    #define M_PileOf SOMObject
#endif /* M_PileOf */

/*
 * End of user-defined types.
 */

#define PileOf_MajorVersion 1
#define PileOf_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define PileOfNewClass PileOfwpsc
#pragma linkage(PileOfwpsc, system)
#define PileOfClassData PileOfwpsd
#define PileOfCClassData PileOfwpsx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <pileof.h>
/*--------------Migration------------*/
#define PileOf_classObj PileOfClassData.classObject
#define _PileOf PileOf_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK PileOfNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(PileOfNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct PileOfClassDataStructure {
	SOMAny *classObject;
	somMToken ValidateDragAndDrop;
	somMToken AddPileOfPage;
	somMToken QueryPileOfInstData;
	somMToken SetPileOfInstData;
} SOMDLINK PileOfClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct PileOfCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK PileOfCClassData;

/*
 * New and Renew macros for PileOf
 */
#define PileOfNew() \
   (_somNew(_PileOf ? _PileOf : PileOfNewClass(PileOf_MajorVersion, PileOf_MinorVersion)))
#define PileOfRenew(buf) \
   (_somRenew(_PileOf ? _PileOf : PileOfNewClass(PileOf_MajorVersion, PileOf_MinorVersion), buf))

/*
 * Override method: wpAddFolderView2Page
 */
#define PileOf_wpAddFolderView2Page(somSelf,hwndNotebook) \
	WPFolder_wpAddFolderView2Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddFolderIncludePage
 */
#define PileOf_wpAddFolderIncludePage(somSelf,hwndNotebook) \
	WPFolder_wpAddFolderIncludePage(somSelf,hwndNotebook)

/*
 * Override method: wpAddSettingsPages
 */
#define PileOf_wpAddSettingsPages(somSelf,hwndNotebook) \
	WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpFilterPopupMenu
 */
#define PileOf_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect) \
	WPObject_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect)

/*
 * Override method: wpModifyPopupMenu
 */
#define PileOf_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define PileOf_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpDragOver
 */
#define PileOf_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)

/*
 * Override method: wpDrop
 */
#define PileOf_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Override method: wpSaveState
 */
#define PileOf_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpRestoreState
 */
#define PileOf_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: somInit
 */
#define PileOf_somInit(somSelf) \
	SOMObject_somInit(somSelf)

/*
 * Override method: somUninit
 */
#define PileOf_somUninit(somSelf) \
	SOMObject_somUninit(somSelf)

/*
 * New Method: ValidateDragAndDrop
 */
typedef BOOL   SOMLINK somTP_PileOf_ValidateDragAndDrop(PileOf *somSelf,
		PDRAGINFO pdrgInfo);
#pragma linkage(somTP_PileOf_ValidateDragAndDrop, system)
typedef somTP_PileOf_ValidateDragAndDrop *somTD_PileOf_ValidateDragAndDrop;
#define somMD_PileOf_ValidateDragAndDrop "::PileOf::ValidateDragAndDrop"
#define PileOf_ValidateDragAndDrop(somSelf,pdrgInfo) \
    (SOM_Resolve(somSelf, PileOf, ValidateDragAndDrop) \
	(somSelf,pdrgInfo))
#ifndef SOMGD_ValidateDragAndDrop
    #if (defined(_ValidateDragAndDrop) || defined(__ValidateDragAndDrop))
        #undef _ValidateDragAndDrop
        #undef __ValidateDragAndDrop
        #define SOMGD_ValidateDragAndDrop 1
    #else
        #define _ValidateDragAndDrop PileOf_ValidateDragAndDrop
    #endif /* _ValidateDragAndDrop */
#endif /* SOMGD_ValidateDragAndDrop */

/*
 * New Method: AddPileOfPage
 */
typedef ULONG   SOMLINK somTP_PileOf_AddPileOfPage(PileOf *somSelf,
		HWND hwndNbk);
#pragma linkage(somTP_PileOf_AddPileOfPage, system)
typedef somTP_PileOf_AddPileOfPage *somTD_PileOf_AddPileOfPage;
#define somMD_PileOf_AddPileOfPage "::PileOf::AddPileOfPage"
#define PileOf_AddPileOfPage(somSelf,hwndNbk) \
    (SOM_Resolve(somSelf, PileOf, AddPileOfPage) \
	(somSelf,hwndNbk))
#ifndef SOMGD_AddPileOfPage
    #if (defined(_AddPileOfPage) || defined(__AddPileOfPage))
        #undef _AddPileOfPage
        #undef __AddPileOfPage
        #define SOMGD_AddPileOfPage 1
    #else
        #define _AddPileOfPage PileOf_AddPileOfPage
    #endif /* _AddPileOfPage */
#endif /* SOMGD_AddPileOfPage */

/*
 * New Method: QueryPileOfInstData
 */
typedef ULONG   SOMLINK somTP_PileOf_QueryPileOfInstData(PileOf *somSelf);
#pragma linkage(somTP_PileOf_QueryPileOfInstData, system)
typedef somTP_PileOf_QueryPileOfInstData *somTD_PileOf_QueryPileOfInstData;
#define somMD_PileOf_QueryPileOfInstData "::PileOf::QueryPileOfInstData"
#define PileOf_QueryPileOfInstData(somSelf) \
    (SOM_Resolve(somSelf, PileOf, QueryPileOfInstData) \
	(somSelf))
#ifndef SOMGD_QueryPileOfInstData
    #if (defined(_QueryPileOfInstData) || defined(__QueryPileOfInstData))
        #undef _QueryPileOfInstData
        #undef __QueryPileOfInstData
        #define SOMGD_QueryPileOfInstData 1
    #else
        #define _QueryPileOfInstData PileOf_QueryPileOfInstData
    #endif /* _QueryPileOfInstData */
#endif /* SOMGD_QueryPileOfInstData */

/*
 * New Method: SetPileOfInstData
 */
typedef void   SOMLINK somTP_PileOf_SetPileOfInstData(PileOf *somSelf,
		ULONG pDtPileOf);
#pragma linkage(somTP_PileOf_SetPileOfInstData, system)
typedef somTP_PileOf_SetPileOfInstData *somTD_PileOf_SetPileOfInstData;
#define somMD_PileOf_SetPileOfInstData "::PileOf::SetPileOfInstData"
#define PileOf_SetPileOfInstData(somSelf,pDtPileOf) \
    (SOM_Resolve(somSelf, PileOf, SetPileOfInstData) \
	(somSelf,pDtPileOf))
#ifndef SOMGD_SetPileOfInstData
    #if (defined(_SetPileOfInstData) || defined(__SetPileOfInstData))
        #undef _SetPileOfInstData
        #undef __SetPileOfInstData
        #define SOMGD_SetPileOfInstData 1
    #else
        #define _SetPileOfInstData PileOf_SetPileOfInstData
    #endif /* _SetPileOfInstData */
#endif /* SOMGD_SetPileOfInstData */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define PileOf_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define PileOf_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define PileOf_wpSetFldrFont WPFolder_wpSetFldrFont
#define PileOf_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define PileOf_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define PileOf_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define PileOf_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define PileOf_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define PileOf_wpPopulate WPFolder_wpPopulate
#define PileOf_wpQueryContent WPFolder_wpQueryContent
#define PileOf_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define PileOf_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define PileOf_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define PileOf_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define PileOf_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define PileOf_wpInitIconPosData WPFolder_wpInitIconPosData
#define PileOf_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define PileOf_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define PileOf_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define PileOf_wpSetFldrSort WPFolder_wpSetFldrSort
#define PileOf_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define PileOf_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define PileOf_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define PileOf_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define PileOf_wpDeleteContents WPFolder_wpDeleteContents
#define PileOf_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define PileOf_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define PileOf_wpSearchFolder WPFolder_wpSearchFolder
#define PileOf_wpContainsFolders WPFolder_wpContainsFolders
#define PileOf_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define PileOf_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define PileOf_wpAddToContent WPFolder_wpAddToContent
#define PileOf_wpDeleteFromContent WPFolder_wpDeleteFromContent
#define PileOf_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define PileOf_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define PileOf_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define PileOf_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define PileOf_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define PileOf_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define PileOf_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define PileOf_wpAddFirstChild WPFolder_wpAddFirstChild
#define PileOf_wpSetRealName WPFileSystem_wpSetRealName
#define PileOf_wpSetType WPFileSystem_wpSetType
#define PileOf_wpQueryType WPFileSystem_wpQueryType
#define PileOf_wpSetAttr WPFileSystem_wpSetAttr
#define PileOf_wpQueryAttr WPFileSystem_wpQueryAttr
#define PileOf_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define PileOf_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define PileOf_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define PileOf_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define PileOf_wpQueryCreation WPFileSystem_wpQueryCreation
#define PileOf_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define PileOf_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define PileOf_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define PileOf_wpQueryEASize WPFileSystem_wpQueryEASize
#define PileOf_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define PileOf_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define PileOf_wpRefresh WPFileSystem_wpRefresh
#define PileOf_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define PileOf_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define PileOf_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define PileOf_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define PileOf_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define PileOf_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define PileOf_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define PileOf_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define PileOf_wpQueryRealName WPFileSystem_wpQueryRealName
#define PileOf_wpQueryFilename WPFileSystem_wpQueryFilename
#define PileOf_wpQueryDisk WPFileSystem_wpQueryDisk
#define PileOf_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define PileOf_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define PileOf_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define PileOf_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define PileOf_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define PileOf_wpAddToObjUseList WPObject_wpAddToObjUseList
#define PileOf_wpAllocMem WPObject_wpAllocMem
#define PileOf_wpAppendObject WPObject_wpAppendObject
#define PileOf_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define PileOf_wpClose WPObject_wpClose
#define PileOf_wpCnrInsertObject WPObject_wpCnrInsertObject
#define PileOf_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define PileOf_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define PileOf_wpConfirmDelete WPObject_wpConfirmDelete
#define PileOf_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define PileOf_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define PileOf_wpCopyObject WPObject_wpCopyObject
#define PileOf_wpCreateAnother WPObject_wpCreateAnother
#define PileOf_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define PileOf_wpCreateShadowObject WPObject_wpCreateShadowObject
#define PileOf_wpDelete WPObject_wpDelete
#define PileOf_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define PileOf_wpDisplayHelp WPObject_wpDisplayHelp
#define PileOf_wpDisplayMenu WPObject_wpDisplayMenu
#define PileOf_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define PileOf_wpDraggedOverObject WPObject_wpDraggedOverObject
#define PileOf_wpDroppedOnObject WPObject_wpDroppedOnObject
#define PileOf_wpEndConversation WPObject_wpEndConversation
#define PileOf_wpFindUseItem WPObject_wpFindUseItem
#define PileOf_wpFormatDragItem WPObject_wpFormatDragItem
#define PileOf_wpFree WPObject_wpFree
#define PileOf_wpFreeMem WPObject_wpFreeMem
#define PileOf_wpHide WPObject_wpHide
#define PileOf_wpInitData WPObject_wpInitData
#define PileOf_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define PileOf_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define PileOf_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define PileOf_wpMoveObject WPObject_wpMoveObject
#define PileOf_wpOpen WPObject_wpOpen
#define PileOf_wpPrintObject WPObject_wpPrintObject
#define PileOf_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define PileOf_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define PileOf_wpQueryConfirmations WPObject_wpQueryConfirmations
#define PileOf_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define PileOf_wpQueryDefaultView WPObject_wpQueryDefaultView
#define PileOf_wpQueryDetailsData WPObject_wpQueryDetailsData
#define PileOf_wpQueryError WPObject_wpQueryError
#define PileOf_wpSetFolder WPObject_wpSetFolder
#define PileOf_wpQueryFolder WPObject_wpQueryFolder
#define PileOf_wpQueryIcon WPObject_wpQueryIcon
#define PileOf_wpQueryIconData WPObject_wpQueryIconData
#define PileOf_wpQueryMinWindow WPObject_wpQueryMinWindow
#define PileOf_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define PileOf_wpQueryStyle WPObject_wpQueryStyle
#define PileOf_wpSetTaskRec WPObject_wpSetTaskRec
#define PileOf_wpFindTaskRec WPObject_wpFindTaskRec
#define PileOf_wpQueryTitle WPObject_wpQueryTitle
#define PileOf_wpRegisterView WPObject_wpRegisterView
#define PileOf_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define PileOf_wpRender WPObject_wpRender
#define PileOf_wpRenderComplete WPObject_wpRenderComplete
#define PileOf_wpReplaceObject WPObject_wpReplaceObject
#define PileOf_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define PileOf_wpRestore WPObject_wpRestore
#define PileOf_wpRestoreData WPObject_wpRestoreData
#define PileOf_wpRestoreLong WPObject_wpRestoreLong
#define PileOf_wpRestoreString WPObject_wpRestoreString
#define PileOf_wpSaveData WPObject_wpSaveData
#define PileOf_wpSaveImmediate WPObject_wpSaveImmediate
#define PileOf_wpSaveDeferred WPObject_wpSaveDeferred
#define PileOf_wpSaveLong WPObject_wpSaveLong
#define PileOf_wpSaveString WPObject_wpSaveString
#define PileOf_wpScanSetupString WPObject_wpScanSetupString
#define PileOf_wpSetConcurrentView WPObject_wpSetConcurrentView
#define PileOf_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define PileOf_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define PileOf_wpSetDefaultView WPObject_wpSetDefaultView
#define PileOf_wpSetError WPObject_wpSetError
#define PileOf_wpSetIconHandle WPObject_wpSetIconHandle
#define PileOf_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define PileOf_wpSetupOnce WPObject_wpSetupOnce
#define PileOf_wpSetIcon WPObject_wpSetIcon
#define PileOf_wpSetIconData WPObject_wpSetIconData
#define PileOf_wpSetMinWindow WPObject_wpSetMinWindow
#define PileOf_wpSetStyle WPObject_wpSetStyle
#define PileOf_wpModifyStyle WPObject_wpModifyStyle
#define PileOf_wpSetTitle WPObject_wpSetTitle
#define PileOf_wpSetup WPObject_wpSetup
#define PileOf_wpSwitchTo WPObject_wpSwitchTo
#define PileOf_wpUnInitData WPObject_wpUnInitData
#define PileOf_wpViewObject WPObject_wpViewObject
#define PileOf_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define PileOf_wpQueryHandle WPObject_wpQueryHandle
#define PileOf_wpUnlockObject WPObject_wpUnlockObject
#define PileOf_wpObjectReady WPObject_wpObjectReady
#define PileOf_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define PileOf_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define PileOf_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define PileOf_wpIsDeleteable WPObject_wpIsDeleteable
#define PileOf_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define PileOf_wpSetObjectID WPObject_wpSetObjectID
#define PileOf_wpQueryObjectID WPObject_wpQueryObjectID
#define PileOf_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define PileOf_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define PileOf_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define PileOf_wpFindViewItem WPObject_wpFindViewItem
#define PileOf_wpLockObject WPObject_wpLockObject
#define PileOf_wpIsLocked WPObject_wpIsLocked
#define PileOf_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define PileOf_wpWaitForClose WPObject_wpWaitForClose
#define PileOf_somDefaultInit SOMObject_somDefaultInit
#define PileOf_somDestruct SOMObject_somDestruct
#define PileOf_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define PileOf_somDefaultAssign SOMObject_somDefaultAssign
#define PileOf_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define PileOf_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define PileOf_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define PileOf_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define PileOf_somDefaultVAssign SOMObject_somDefaultVAssign
#define PileOf_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define PileOf_somFree SOMObject_somFree
#define PileOf_somGetClass SOMObject_somGetClass
#define PileOf_somGetClassName SOMObject_somGetClassName
#define PileOf_somGetSize SOMObject_somGetSize
#define PileOf_somIsA SOMObject_somIsA
#define PileOf_somIsInstanceOf SOMObject_somIsInstanceOf
#define PileOf_somRespondsTo SOMObject_somRespondsTo
#define PileOf_somDispatch SOMObject_somDispatch
#define PileOf_somClassDispatch SOMObject_somClassDispatch
#define PileOf_somCastObj SOMObject_somCastObj
#define PileOf_somResetObj SOMObject_somResetObj
#define PileOf_somDispatchV SOMObject_somDispatchV
#define PileOf_somDispatchL SOMObject_somDispatchL
#define PileOf_somDispatchA SOMObject_somDispatchA
#define PileOf_somDispatchD SOMObject_somDispatchD
#define PileOf_somPrintSelf SOMObject_somPrintSelf
#define PileOf_somDumpSelf SOMObject_somDumpSelf
#define PileOf_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_PileOf_h */

#ifndef SOM_M_PileOf_h
#define SOM_M_PileOf_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_PileOf
#define M_PileOf SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_PileOf_MajorVersion 1
#define M_PileOf_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_PileOfNewClass PileOfwpsc
#pragma linkage(PileOfwpsc, system)
#define M_PileOfClassData PileOfwpsd
#define M_PileOfCClassData PileOfwpsx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_PileOf_classObj M_PileOfClassData.classObject
#define _M_PileOf M_PileOf_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_PileOfNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_PileOfNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_PileOfClassDataStructure {
	SOMAny *classObject;
} SOMDLINK M_PileOfClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_PileOfCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_PileOfCClassData;

/*
 * New and Renew macros for M_PileOf
 */
#define M_PileOfNew() \
   (_somNew(_M_PileOf ? _M_PileOf : M_PileOfNewClass(M_PileOf_MajorVersion, M_PileOf_MinorVersion)))
#define M_PileOfRenew(buf) \
   (_somRenew(_M_PileOf ? _M_PileOf : M_PileOfNewClass(M_PileOf_MajorVersion, M_PileOf_MinorVersion), buf))

/*
 * Override method: wpclsQueryTitle
 */
#define M_PileOf_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsInitData
 */
#define M_PileOf_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_PileOf_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_PileOf_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_PileOf_wpclsQueryIconDataN M_WPFolder_wpclsQueryIconDataN
#define M_PileOf_wpclsQueryIconN M_WPFolder_wpclsQueryIconN
#define M_PileOf_wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
#define M_PileOf_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_PileOf_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_PileOf_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_PileOf_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_PileOf_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_PileOf_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_PileOf_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_PileOf_wpclsNew M_WPObject_wpclsNew
#define M_PileOf_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_PileOf_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_PileOf_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_PileOf_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_PileOf_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_PileOf_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_PileOf_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_PileOf_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_PileOf_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_PileOf_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_PileOf_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_PileOf_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_PileOf_wpclsSetError M_WPObject_wpclsSetError
#define M_PileOf_wpclsQueryError M_WPObject_wpclsQueryError
#define M_PileOf_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_PileOf_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_PileOf_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_PileOf_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_PileOf_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_PileOf_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_PileOf_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_PileOf_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_PileOf_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_PileOf_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_PileOf_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_PileOf_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_PileOf__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_PileOf__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_PileOf__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_PileOf__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_PileOf_somNew SOMClass_somNew
#define M_PileOf_somNewNoInit SOMClass_somNewNoInit
#define M_PileOf_somRenew SOMClass_somRenew
#define M_PileOf_somRenewNoInit SOMClass_somRenewNoInit
#define M_PileOf_somRenewNoZero SOMClass_somRenewNoZero
#define M_PileOf_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_PileOf_somAllocate SOMClass_somAllocate
#define M_PileOf_somDeallocate SOMClass_somDeallocate
#define M_PileOf__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_PileOf__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_PileOf_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_PileOf_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_PileOf_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_PileOf_somInitClass SOMClass_somInitClass
#define M_PileOf_somInitMIClass SOMClass_somInitMIClass
#define M_PileOf_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_PileOf_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_PileOf_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_PileOf_somClassReady SOMClass_somClassReady
#define M_PileOf_somGetApplyStub SOMClass_somGetApplyStub
#define M_PileOf_somGetClassData SOMClass_somGetClassData
#define M_PileOf_somSetClassData SOMClass_somSetClassData
#define M_PileOf_somGetClassMtab SOMClass_somGetClassMtab
#define M_PileOf_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_PileOf_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_PileOf_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_PileOf_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_PileOf_somGetMemberToken SOMClass_somGetMemberToken
#define M_PileOf_somGetMethodData SOMClass_somGetMethodData
#define M_PileOf_somGetRdStub SOMClass_somGetRdStub
#define M_PileOf_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_PileOf_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_PileOf_somGetMethodToken SOMClass_somGetMethodToken
#define M_PileOf_somGetName SOMClass_somGetName
#define M_PileOf_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_PileOf_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_PileOf_somGetNumMethods SOMClass_somGetNumMethods
#define M_PileOf_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_PileOf_somGetParent SOMClass_somGetParent
#define M_PileOf_somGetParents SOMClass_somGetParents
#define M_PileOf_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_PileOf_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_PileOf_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_PileOf_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_PileOf_somFindMethod SOMClass_somFindMethod
#define M_PileOf_somFindMethodOk SOMClass_somFindMethodOk
#define M_PileOf_somFindSMethod SOMClass_somFindSMethod
#define M_PileOf_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_PileOf_somLookupMethod SOMClass_somLookupMethod
#define M_PileOf_somCheckVersion SOMClass_somCheckVersion
#define M_PileOf_somDescendedFrom SOMClass_somDescendedFrom
#define M_PileOf_somSupportsMethod SOMClass_somSupportsMethod
#define M_PileOf_somDefinedMethod SOMClass_somDefinedMethod
#define M_PileOf_somOverrideMtab SOMClass_somOverrideMtab
#define M_PileOf_somDefaultInit SOMObject_somDefaultInit
#define M_PileOf_somDestruct SOMObject_somDestruct
#define M_PileOf_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_PileOf_somDefaultAssign SOMObject_somDefaultAssign
#define M_PileOf_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_PileOf_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_PileOf_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_PileOf_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_PileOf_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_PileOf_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_PileOf_somInit SOMObject_somInit
#define M_PileOf_somFree SOMObject_somFree
#define M_PileOf_somUninit SOMObject_somUninit
#define M_PileOf_somGetClass SOMObject_somGetClass
#define M_PileOf_somGetClassName SOMObject_somGetClassName
#define M_PileOf_somGetSize SOMObject_somGetSize
#define M_PileOf_somIsA SOMObject_somIsA
#define M_PileOf_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_PileOf_somRespondsTo SOMObject_somRespondsTo
#define M_PileOf_somDispatch SOMObject_somDispatch
#define M_PileOf_somClassDispatch SOMObject_somClassDispatch
#define M_PileOf_somCastObj SOMObject_somCastObj
#define M_PileOf_somResetObj SOMObject_somResetObj
#define M_PileOf_somDispatchV SOMObject_somDispatchV
#define M_PileOf_somDispatchL SOMObject_somDispatchL
#define M_PileOf_somDispatchA SOMObject_somDispatchA
#define M_PileOf_somDispatchD SOMObject_somDispatchD
#define M_PileOf_somPrintSelf SOMObject_somPrintSelf
#define M_PileOf_somDumpSelf SOMObject_somDumpSelf
#define M_PileOf_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_PileOf_h */
