/*******************************************************************************
* FILE NAME: NbkPage.hpp                                                       *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     NbkPage                                                                  *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _NBKPAGE_
#define _NBKPAGE_  

class NbkPage;

#ifndef _IMCELCV_
#include <imcelcv.hpp>
#endif

class IStaticText;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#include "NbkPage.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for NbkPage
//*****************************************************************************
class NbkPage : public IMultiCellCanvas {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   NbkPage(
      unsigned long id = WND_NbkPage,
      IWindow * parent = IWindow::desktopWindow(),
      IWindow * owner = 0,
      const IRectangle & rect = defaultFramingSpec(),
      const IMultiCellCanvas::Style & style = IMultiCellCanvas::defaultStyle());

   virtual  ~NbkPage();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static IRectangle defaultFramingSpec();
   virtual NbkPage & initializePart();
   NbkPage * getMultiCellCanvas() { return this; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   IStaticText * iStaticText1;
   static unsigned long partWindowId;


};   //NbkPage


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
