/*******************************************************************************
* FILE NAME: NbkPage.h                                                         *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     NbkPage                                                                  *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_NbkPage
#define WND_NbkPage  VBBASEWINDOWID
#endif

#define WNDOFFSET_NbkPage_MultiCellCanvas  0
#define WND_NbkPage_MultiCellCanvas  WND_NbkPage

#define WNDOFFSET_NbkPage_StaticText1  1
#define WND_NbkPage_StaticText1  WND_NbkPage + WNDOFFSET_NbkPage_StaticText1


