/*******************************************************************************
* FILE NAME: NbkTest.hpp                                                       *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     NbkTest                                                                  *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _NBKTEST_
#define _NBKTEST_  

class NbkTest;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

class INotebook;
class IVBNotebookPage;
class IMultiCellCanvas;
class IPushButton;
class IStaticText;
class IEntryField;
class NbkPage;
#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

class NbkTestConn0;
class NbkTestConn1;
class NbkTestConn3;
#include "NbkTest.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for NbkTestNewPageFactFactory
//*****************************************************************************
class NbkTestNewPageFactFactory : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   NbkTestNewPageFactFactory(unsigned long anId);

   virtual  ~NbkTestNewPageFactFactory();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   NbkPage * create();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId newObjectCreatedId;

protected:
private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   unsigned long partWindowId;


};   //NbkTestNewPageFactFactory


//*****************************************************************************
// Class definition for NbkTest
//*****************************************************************************
class NbkTest : public IFrameWindow {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   NbkTest(
      unsigned long id = WND_NbkTest,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = IFrameWindow::defaultStyle ( ),
      const char* title = defaultTitle());

   virtual  ~NbkTest();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static IString defaultTitle();
   virtual NbkTest & initializePart();
   NbkTest * getFrameWindow() { return this; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   INotebook * iNotebook1;
   IVBNotebookPage * iVBNotebookPage1;
   IMultiCellCanvas * iMultiCellCanvas2;
   IPushButton * iPushButton1;
   IStaticText * iStaticText1;
   IEntryField * iEntryField4;
   NbkTestNewPageFactFactory * iNewPageFact;
   NbkTestConn0 * conn0;
   NbkTestConn1 * conn1;
   NbkTestConn3 * conn3;
   static unsigned long partWindowId;


};   //NbkTest


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
