/*******************************************************************************
* FILE NAME: NbkTest.h                                                         *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     NbkTest                                                                  *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_NbkTest
#define WND_NbkTest  VBBASEWINDOWID
#endif

#define WNDOFFSET_NbkTest_FrameWindow  0
#define WND_NbkTest_FrameWindow  WND_NbkTest

#define WND_NbkTest_Notebook1  IC_FRAME_CLIENT_ID


#define WNDOFFSET_NbkTest_MultiCellCanvas2  1
#define WND_NbkTest_MultiCellCanvas2  WND_NbkTest + WNDOFFSET_NbkTest_MultiCellCanvas2

#define WNDOFFSET_NbkTest_PushButton1  2
#define WND_NbkTest_PushButton1  WND_NbkTest + WNDOFFSET_NbkTest_PushButton1

#define WNDOFFSET_NbkTest_StaticText1  3
#define WND_NbkTest_StaticText1  WND_NbkTest + WNDOFFSET_NbkTest_StaticText1

#define WNDOFFSET_NbkTest_EntryField4  4
#define WND_NbkTest_EntryField4  WND_NbkTest + WNDOFFSET_NbkTest_EntryField4

#define WNDOFFSET_NbkTest_NewPageFact  5
#define WND_NbkTest_NewPageFact  WND_NbkTest + WNDOFFSET_NbkTest_NewPageFact


