'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' CICS Client Visual Basic constant file for epiinq.bms
'
' Generated by CICS BMS Conversion Utility - Version 1.0
' This file can be loaded into a code module

' MAPINQ1Map constants
Public Const MAPINQ1 = "0.23.81.88.104.111.138.148.327.343.722.734.749.761.778.788.1122.1134.1178.1188.1619.1653.1655.1846.1870"
Public Const MAPINQ1_DTITLE = 81
Public Const MAPINQ1_DATE = 88
Public Const MAPINQ1_TTITLE = 104
Public Const MAPINQ1_TIME = 111
Public Const MAPINQ1_MTITLE = 138
Public Const MAPINQ1_MAPNAME = 148
Public Const MAPINQ1_PTITLE = 327
Public Const MAPINQ1_PRODNAM = 343
Public Const MAPINQ1_STITLE = 722
Public Const MAPINQ1_SYSID = 734
Public Const MAPINQ1_FTITLE = 749
Public Const MAPINQ1_FACILTY = 761
Public Const MAPINQ1_NTITLE = 778
Public Const MAPINQ1_NETNAME = 788
Public Const MAPINQ1_ATITLE = 1122
Public Const MAPINQ1_APPLID = 1134
Public Const MAPINQ1_UTITLE = 1178
Public Const MAPINQ1_USERID = 1188
Public Const MAPINQ1_QUESTN = 1619
Public Const MAPINQ1_ANSWER = 1653


' MAPINQ2Map constants
Public Const MAPINQ2 = "0.7.137.148.487.503.519.530.1849"
Public Const MAPINQ2_MTITLE = 137
Public Const MAPINQ2_MAPNAME = 148
Public Const MAPINQ2_TTITLE = 487
Public Const MAPINQ2_TRANCDE = 503
Public Const MAPINQ2_PTITLE = 519
Public Const MAPINQ2_PROGNAM = 530

