/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class krl1 */

#ifndef _Included_krl1
#define _Included_krl1
struct Hjava_lang_String;

#pragma pack(4)

typedef struct Classkrl1 {
    long a;
    long b;
    struct Hjava_lang_String *c;
} Classkrl1;
HandleTo(krl1);

#pragma pack()

#ifdef __cplusplus
extern "C" {
#endif
extern long krl1_addup(struct Hkrl1 *,long,long);
#ifdef __cplusplus
}
#endif
#endif
