/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class krl1 */
/* SYMBOL: "krl1/addup(II)I", Java_krl1_addup_stub */
 stack_item * _Export _Optlink Java_krl1_addup_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long krl1_addup(void *,long,long);
	_P_[0].i = krl1_addup(_P_[0].p,((_P_[1].i)),((_P_[2].i)));
	return _P_ + 1;
}
