/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class Pal */
/* SYMBOL: "Pal/findPalindrome(I)Z", Java_Pal_findPalindrome_stub */
 stack_item * _Optlink _Export Java_Pal_findPalindrome_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long Pal_findPalindrome(void *,long);
	_P_[0].i = (Pal_findPalindrome(_P_[0].p,((_P_[1].i))) ? TRUE : FALSE);
	return _P_ + 1;
}
