/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class Pal */

#ifndef _Included_Pal
#define _Included_Pal
struct Hjava_lang_String;

typedef struct ClassPal {
    struct Hjava_lang_String *str;
} ClassPal;
HandleTo(Pal);

#ifdef __cplusplus
extern "C" {
#endif
extern /*boolean*/ long Pal_findPalindrome(struct HPal *,long);
#ifdef __cplusplus
}
#endif
#endif
