/*
 *                    NOTICE TO USERS OF THE SOURCE CODE
 *
 * THE SOURCE CODE EXAMPLES PROVIDED BY IBM ARE ONLY INTENDED TO ASSIST
 * IN THE DEVELOPMENT OF A 24 BIT DDX.
 *
 * INTERNATIONAL BUSINESS MACHINES CORPORATION PROVIDES THE SOURCE CODE
 * EXAMPLES, BOTH INDIVIDUALLY AND AS ONE OR MORE GROUPS, "AS IS" WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT
 * LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE.
 *
 *   FUNCTIONS: none
 *
 */
/*
 * Icecube cursor private area.
 */
typedef struct _CursPriv {
   int          type;
   u_long       *pGlyph;
} CursPriv,  *CursPrivPtr;

#define CROSSHAIR_TYPE  1
#define X_CURSOR_TYPE   2
#define THREECOLOR_TYPE 3

#define CURSOR_OFF  0x0
#define CURSOR_ON   0x1
