/***********************************************************************/
/*                                                                     */
/* DESCRIPTIVE NAME   CICS Client ECI Test for Windows                 */
/*                                                                     */
/***********************************************************************/

 #define ECI_CLASS  "EciTestClass"
 #define ECI_MENU   "EciTestMenu"

 #define ECI_MSG    WM_USER + 10

 #define ECI_ITEM_EXIT  200
 #define CALL_ECI       210
 #define ECI_ITEM_CLEAR 220
 #define ECI_ITEM_NULL  230                    
 #define PARSE_PARMS    240                    

