@rem ****************************************************************
@rem sample settings for COBOL and CICS Client for Windows
@rem assumes COBOL installed on C drive with default library names
@rem and CICS Client for Windows installed into C:\CICSCLIW
@rem ****************************************************************
set cobcpy=c:\cicscliw\copybook
SET COBDIR=C:\COBOL\LBR;C:\COBOL\EXEDLL;
SET LIB=C:\COBOL\LIB;c:\cicscliw\lib;
SET COBHNF=C:\COBOL\ON-LINE;
SET INCLUDE=C:\COBOL\INC;c:\cicscliw\include
