        TITLE   INT3386.ASM
        .386
        .387
CODE32  SEGMENT DWORD USE32 PUBLIC 'CODE'
CODE32  ENDS
DATA32  SEGMENT DWORD USE32 PUBLIC 'DATA'
DATA32  ENDS
CONST32 SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST32 ENDS
BSS32   SEGMENT DWORD USE32 PUBLIC 'BSS'
BSS32   ENDS
DGROUP  GROUP CONST32, BSS32, DATA32
        ASSUME  CS:FLAT, DS:FLAT, SS:FLAT, ES:FLAT

CODE32  SEGMENT
        ALIGN 04H
        PUBLIC _int3
_int3   PROC
        INT     3
        RET
_int3   ENDP

        ALIGN 04H
        PUBLIC int3
int3    PROC
        INT     3
        RET
int3    ENDP
CODE32  ENDS
END
