#ifndef _DTS_HH_INCLUDED_icluixmp
#define _DTS_HH_INCLUDED_icluixmp
/* Start Class IcluiExample */

// This file was generated by the IBM "DirectToSOM" emitter for C++ (V1.83)
// Generated at 10/11/95 12:22:43 EDT
// This is class: IcluiExample
// Mangled class name: IcluiExample
// SE: May 19/94

#include <som.hh>

     #pragma SOMAsDefault(on)
class SOMClass;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class SOMObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPFolder;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPAbstract;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_IcluiExample;
     #pragma SOMAsDefault(pop)

     #define INCL_WIN
     #define INCL_DOS

     #include <os2.h>
#include <wpabs.hh>
#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class IcluiExample : public WPAbstract {

        #pragma SOMClassName(*, "IcluiExample")
        #pragma SOMNoMangling(*)
        #pragma SOMNonDTS(*)

     #pragma SOMClassName (IcluiExample, "IcluiExample")
     #pragma SOMMetaClass (IcluiExample, M_IcluiExample)
     #pragma SOMClassVersion (IcluiExample, 1, 2)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual ULONG wpQueryaVariable();
     virtual void wpSetaVariable(ULONG value);
     virtual void wpRefreshViews();
     virtual BOOL wpModifyPopupMenu(HWND hwndMenu, HWND hwndCnr,
                                    ULONG iPosition);
     virtual BOOL wpAddSettingsPages(HWND hwndNotebook);
     virtual BOOL wpRestoreState(ULONG ulReserved);
     virtual BOOL wpSaveState();
     virtual HWND wpOpen(HWND hwndCnr, ULONG ulView, ULONG param);
     virtual BOOL wpMenuItemSelected(HWND hwndFrame, ULONG ulMenuId);
  private :
     ULONG aVariable;

     #pragma SOMReleaseOrder ( \
                              "wpQueryaVariable", \
                              "wpSetaVariable", \
                              "wpRefreshViews")
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End IcluiExample */
/* Start Class M_IcluiExample */

#include <wpabs.hh>
#include <somcls.hh>
#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class M_IcluiExample : public M_WPAbstract {

        #pragma SOMClassName(*, "M_IcluiExample")
        #pragma SOMNoMangling(*)
        #pragma SOMNonDTS(*)

     #pragma SOMClassVersion (M_IcluiExample, 1, 2)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual void wpclsInitData();
     virtual PSZ wpclsQueryTitle();
     virtual ULONG wpclsQueryDefaultView();
     virtual ULONG wpclsQueryStyle();
     virtual BOOL wpclsCreateDefaultTemplates(WPObject* Folder);
     #pragma SOMReleaseOrder ()
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End M_IcluiExample */
#endif /* _DTS_HH_INCLUDED_icluixmp */
