#ifndef _DTS_HH_INCLUDED_wpabs
#define _DTS_HH_INCLUDED_wpabs
/* Start Class WPAbstract */

// This file was generated by the IBM "DirectToSOM" emitter for C++ (V1.77)
// Generated at 08/16/95 09:05:45 EDT
// This is class: WPAbstract
// Mangled class name: WPAbstract
// SE: May 19/94

#include <som.hh>

     #pragma SOMAsDefault(on)
class SOMClass;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class SOMObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPFolder;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class WPObject;
     #pragma SOMAsDefault(pop)
     #pragma SOMAsDefault(on)
class M_WPAbstract;
     #pragma SOMAsDefault(pop)
#include <wpobject.hh>
#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class WPAbstract : public WPObject {

        #pragma SOMClassName(*, "WPAbstract")
        #pragma SOMNoMangling(*)
        #pragma SOMNonDTS(*)

     #pragma SOMClassName (WPAbstract, "WPAbstract")
     #pragma SOMMetaClass (WPAbstract, M_WPAbstract)
     #pragma SOMClassVersion (WPAbstract, 1, 2)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual HOBJECT wpQueryHandle();
     virtual BOOL wpSaveImmediate();
     virtual BOOL wpSaveState();
     virtual BOOL wpRestoreState(ULONG ulReserved);
     virtual BOOL wpSetTitle(PSZ pszNewTitle);
     virtual WPObject* wpCopyObject(WPFolder* Folder, BOOL fLock);
     virtual BOOL wpMoveObject(WPFolder* Folder);
     virtual HPOINTER wpQueryIcon();
     virtual ULONG wpQueryIconData(PICONINFO pIconInfo);
     virtual BOOL wpSetIconData(PICONINFO pIconInfo);
     virtual MRESULT wpDragOver(HWND hwndCnr, PDRAGINFO pdrgInfo);
     virtual BOOL32 wpReplaceObject(WPObject* targetObject, BOOL32 fMove);
     virtual ULONG wpQueryNameClashOptions(ULONG menuID);
     #pragma SOMReleaseOrder ()
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End WPAbstract */
/* Start Class M_WPAbstract */

#include <wpobject.hh>
#include <somcls.hh>
#pragma SOMNonDTS(on)

#pragma SOMAsDefault(on)
class M_WPAbstract : public M_WPObject {

        #pragma SOMClassName(*, "M_WPAbstract")
        #pragma SOMNoMangling(*)
        #pragma SOMNonDTS(*)

     #pragma SOMClassVersion (M_WPAbstract, 1, 2)
     #pragma SOMCallstyle (oidl)
     #pragma SOMAsDefault(off)
     #pragma SOMAsDefault(pop)
  public :
     virtual ULONG wpclsQuerySetting(PSZ pszSetting, PVOID pValue,
                                     ULONG ulValueLen);
     virtual BOOL wpclsSetSetting(PSZ pszSetting, PVOID pValue);
     virtual PSZ wpclsQueryTitle();
     #pragma SOMReleaseOrder ( \
                              *, \
                              *, \
                              *, \
                              "wpclsQuerySetting", \
                              "wpclsSetSetting")
};
#pragma SOMAsDefault(pop)

     #pragma SOMNonDTS(pop)
/* End M_WPAbstract */
#endif /* _DTS_HH_INCLUDED_wpabs */
