//---------------------------------------------------------------------------
// This code is generated by IBM VisualAge for Java Data Access Builder.
// WARNING: User modifications will be lost on next code generation.
//---------------------------------------------------------------------------
package Isvapps;

import COM.ibm.ivj.eab.data.*;
import java.io.*;
import java.awt.*;

//----------------------------------------------------------------
//
// IsvappsDatastore - connect/disconnect from database
//
//----------------------------------------------------------------

public class IsvappsDatastore extends DatastoreJDBC implements Serializable
{

  public IsvappsDatastore() {
    setDriver("COM.ibm.db2.jdbc.app.DB2Driver");
    setURL("jdbc:db2:APPSGUID");
    if (Isvapps.getDefaultDatastore() == null)  Isvapps.setDefaultDatastore(this);
  }

  public IsvappsDatastore(String driver) {
    setDriver(driver);
    setURL("jdbc:db2:APPSGUID");
    if (Isvapps.getDefaultDatastore() == null)  Isvapps.setDefaultDatastore(this);
  }

  public void setAsDefaultDatastore() {
    Isvapps.setDefaultDatastore(this);
  }

  //
  // These methods are used for serialization:
  //
  private void writeObject(ObjectOutputStream s) throws IOException {
    s.defaultWriteObject();
  }

  private void readObject(ObjectInputStream s) throws IOException, ClassNotFoundException {
    s.defaultReadObject();
    if (Isvapps.getDefaultDatastore() == null) setAsDefaultDatastore();
  }

}
