//------------------------------------------------------------------------
// This code is generated by IBM VisualAge for Java Data Access Builder.
// WARNING: User modifications will be lost on next code generation.
//------------------------------------------------------------------------

package Isvapps;

import COM.ibm.ivj.eab.data.*;
import java.math.*;
import java.beans.*;
import java.sql.*;

public class IsvappsDataIdForm extends DataAccessObjectForm
{
  public IsvappsDataIdForm()
  {
     this(new IsvappsDataId());
  }
  public IsvappsDataIdForm( IsvappsDataId aDataId )
  {
     super( attributeNames
          , attributeLabels
          , attributeNullables
          , attributeClasses
          , attributeWidths );
     setTarget(aDataId);
  }

  public IsvappsDataId getTargetAsIsvappsDataId()
  {
    return (IsvappsDataId) getTarget();
  }

  public void setTargetAsIsvappsDataId( IsvappsDataId aTarget )
  {
    super.setTarget( (DataAccessObject) aTarget );
  }
  protected DataAccessObject validateTarget(DataAccessObject aTarget)
  {
    return (IsvappsDataId) aTarget;
  }

  public static Class[] attributeClasses = {
                      String.class 
    };
  private static String[] attributeLabels = {
                "product_id"  };
  private static String[] attributeNames = {
                "product_id"  };
  private static boolean[] attributeNullables = {
                false  };
  private static int[] attributeWidths = {
                10  };
  public void attributeFromEditor(String attributeName, PropertyEditor editor) throws DAException
  {
    if ( editor == null )
      return;
    else if ( attributeName.equals("product_id") )
         getTargetAsIsvappsDataId().setProduct_id((String)editor.getValue());
 
  }
  public void attributeIntoEditor(String attributeName, PropertyEditor editor)
  {
    if ( editor == null )
      return;
    else if ( attributeName.equals("product_id") )
      editor.setValue(getTargetAsIsvappsDataId().getProduct_id());
 
  }

}
