//------------------------------------------------------------------------
// This code is generated by IBM VisualAge for Java Data Access Builder.
// WARNING: User modifications will be lost on next code generation.
//------------------------------------------------------------------------

package Isvapps;

import java.lang.*;
import COM.ibm.ivj.eab.data.*;
import java.beans.*;

public class IsvappsResultForm extends DataAccessResultForm
{
   public IsvappsResultForm()
   {
      this( new IsvappsManager() );
   }
   public IsvappsResultForm(IsvappsManager aManager)
   {
      super(attributeLabels);
      setManager(aManager);
   }
   private static String[] attributeLabels = {
            "product_id",
            "product_name",
            "short_name",
            "description",
            "classification",
            "type",
            "platforms",
            "level",
            "file",
            "size",
            "supplier_id",
            "create_date",
            "url",
            "readme"  };
   // only allow labels to be changed, not the number of columns
   public void setColumns( String[] labels )
   {
      if ( labels.length != attributeLabels.length )
         throw new IllegalArgumentException();
      else
         super.setColumns(labels);
   }

}
