//------------------------------------------------------------------------
// This code is generated by IBM VisualAge for Java Data Access Builder.
// WARNING: User modifications will be lost on next code generation.
//------------------------------------------------------------------------

package IsvappsRMI;

import java.lang.*;
import java.math.*;
import java.util.*;
import java.sql.*;
import COM.ibm.ivj.eab.data.*;
import java.io.Serializable;
import java.beans.*;

//----------------------------------------------------------------
//
// IsvappsDataId - persistent object class data identifier
//
//----------------------------------------------------------------

public class IsvappsDataId extends PODataId implements Cloneable, Serializable
{
 //----------------------------------------------------------------
 // Constructors
 //----------------------------------------------------------------
  public IsvappsDataId() {}

  public IsvappsDataId( String aProduct_id ) {
    _setProduct_id(aProduct_id); 
  }

 //----------------------------------------------------------------
 // clone - returns a copy of the object
 //----------------------------------------------------------------
  public Object clone() {
    IsvappsDataId obj = new IsvappsDataId();

    obj.iProduct_id = iProduct_id; 

    return obj;
  }

 //----------------------------------------------------------------
 // equals - compares itself with another object
 //----------------------------------------------------------------
  public boolean equals(Object anObject) {
    if ( !(anObject instanceof IsvappsDataId) ) return false;
    IsvappsDataId aDataId = (IsvappsDataId)anObject;

    if ( iProduct_id != aDataId.iProduct_id ) {
       if ( iProduct_id == null || aDataId.iProduct_id == null) return false;
       else if ( !iProduct_id.equals( aDataId.iProduct_id ) ) return false;
     } 

    return true;
  }

 //----------------------------------------------------------------
 // Display methods
 //----------------------------------------------------------------
  public String toString(String aseparator) {
    return (getProduct_id());
  }
  public String toString() { return toString("."); }

 //----------------------------------------------------------------
 // IsvappsDataId Attributes and methods
 //----------------------------------------------------------------

  /*--------------------------------------------------------------
     IsvappsDataId product_id access methods
     This attribute is mapped to PRODUCT_ID.
    --------------------------------------------------------------*/
   private String iProduct_id = null;

   public String getProduct_id() { return iProduct_id; }
   public void setProduct_id(String aProduct_id) { 
     String temp = iProduct_id; 
     modified[0] = true;
     iProduct_id = aProduct_id; 
     setModified(true);
     _changes.firePropertyChange("product_id",  temp, aProduct_id); 
   } 

   void _setProduct_id(String aProduct_id) {
     if (_sendingAttributeEvents) {
       String temp = iProduct_id; 
       iProduct_id = aProduct_id; 
       _changes.firePropertyChange("product_id",  temp, aProduct_id); 
     } else {
       iProduct_id = aProduct_id;
     }
   } 

   public boolean isProduct_idNullable() { return false; } 

  public String[] getAttributeStrings()
  {
    String[] s = {getProduct_id()  };
     return (s);
  }
  public Object[] getAttributes()
  {
    Object[] o = {getProduct_id()  };
     return (o);
  }

  public void setModified(boolean enable) {
    if ( !enable ) {
      for(int i=0; i < modified.length; i++) modified[i] = false;
    }
    super.setModified(enable);
  }

  boolean modified[] = { false };

} 
